server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simpleerp?useSSL=false&serverTimezone=UTC
    username: root
    password: sua_senha
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop  # Use 'update' em produção
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
  secret: suaChaveSuperSecreta123!@#  # Mude para algo mais seguro
  expiration: 86400000  # 24 horas em ms

# OpenAPI / Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs